import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author victus
 */
public class randevu extends javax.swing.JFrame {

   
    /**
     * Creates new form randevu
     */
    public randevu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        kimlik_num = new javax.swing.JLabel();
        ad_soyad = new javax.swing.JLabel();
        doktor = new javax.swing.JLabel();
        muayene_saati = new javax.swing.JLabel();
        telefon_no = new javax.swing.JLabel();
        kimliknumarası = new javax.swing.JTextField();
        adsoyad = new javax.swing.JTextField();
        telefonno = new javax.swing.JTextField();
        doktorlar = new javax.swing.JComboBox<>();
        button_randevu = new javax.swing.JButton();
        muayenesaati = new javax.swing.JComboBox<>();
        zorunlualan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kimlik_num.setText("Kimlik Numarası:");

        ad_soyad.setText("Adı Soyadı:");

        doktor.setText("Doktor:");

        muayene_saati.setText("Muayene Saati:");

        telefon_no.setText("Telefon No:");

        kimliknumarası.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                kimliknumarasıMouseMoved(evt);
            }
        });
        kimliknumarası.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kimliknumarasıActionPerformed(evt);
            }
        });

        telefonno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonnoActionPerformed(evt);
            }
        });

        doktorlar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lütfen Seçiniz", "Dr. Levent Kale", "Dr. Sevim Tilki", "Dr. Ayşe Kabasakal", "Dr. Erdem Torun", "Dr. Kadriye Kodaman", "Dr. Fahrettin Kağıt" }));

        button_randevu.setText("Randevu Al");
        button_randevu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_randevuActionPerformed(evt);
            }
        });

        muayenesaati.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lütfen Seçiniz", "09:00-09:30", "10:00-10:30", "11:00-11:30", "13:00-13:30", "14:00-14:30", "15:00-15:30", " ", " " }));

        zorunlualan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        zorunlualan.setForeground(new java.awt.Color(204, 51, 0));
        zorunlualan.setText("*");
        zorunlualan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                zorunlualanMouseMoved(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("*");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("*");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("*");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 51, 0));
        jLabel6.setText("* Zorunlu Alanları Doldurunuz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kimlik_num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ad_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doktor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muayene_saati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefon_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(button_randevu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kimliknumarası)
                                    .addComponent(adsoyad)
                                    .addComponent(telefonno)
                                    .addComponent(doktorlar, 0, 169, Short.MAX_VALUE)
                                    .addComponent(muayenesaati, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zorunlualan)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kimlik_num)
                    .addComponent(kimliknumarası, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zorunlualan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_soyad)
                    .addComponent(adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefon_no)
                    .addComponent(telefonno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doktor)
                    .addComponent(doktorlar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muayene_saati)
                    .addComponent(muayenesaati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addComponent(button_randevu)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonnoActionPerformed

    private void button_randevuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_randevuActionPerformed
    //Girilen değerleri metot ataması yaparak ekrana option pane ile yazdırdım.    
        String mesaj=String.format("Kimlik Numarası: %s \nAd Soyad: %s \nTelefon No: %s \nDoktor: %s \nMuayene Saati: %s saatine randevunuz başarıyla oluşturulmuştur.",kimliknumarası.getText(),adsoyad.getText(),telefonno.getText(),doktorlar.getSelectedItem(),muayenesaati.getSelectedItem());
        jOptionPane1.showMessageDialog(null, mesaj);
        
        
      
        
        
    }//GEN-LAST:event_button_randevuActionPerformed

    private void kimliknumarasıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kimliknumarasıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kimliknumarasıActionPerformed

    private void zorunlualanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zorunlualanMouseMoved

    }//GEN-LAST:event_zorunlualanMouseMoved

    private void kimliknumarasıMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kimliknumarasıMouseMoved
    
        zorunlualan.setVisible(true);
    }//GEN-LAST:event_kimliknumarasıMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new randevu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad_soyad;
    private javax.swing.JTextField adsoyad;
    private javax.swing.JButton button_randevu;
    private javax.swing.JLabel doktor;
    private javax.swing.JComboBox<String> doktorlar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel kimlik_num;
    private javax.swing.JTextField kimliknumarası;
    private javax.swing.JLabel muayene_saati;
    private javax.swing.JComboBox<String> muayenesaati;
    private javax.swing.JLabel telefon_no;
    private javax.swing.JTextField telefonno;
    private javax.swing.JLabel zorunlualan;
    // End of variables declaration//GEN-END:variables
}
